server:
#  port: 80
  port: ${PORT:8080}
rent:
  oss:
    access-key: "EdZE04QMFz_sQGYKFUl6expkzHAWBlhYnfK-gL8P"
    secret-key: "deNAtNolkpr4rrSOHNHnUl2KBYir1DzECozQe5bg"
    bucket: "hospilink"
  jwt:
    #密钥
    secret: "powernode2023powernode2023powernode2023"
    #有效时长,单位秒
    expire: 14400
    header: "Authorization"
    prefix: "Bearer "

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-c6jgmsik.sql.tencentcdb.com:20167/springboot_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&tcpKeepAlive=true
#    url: jdbc:mysql://10.18.105.70:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&tcpKeepAlive=true
    username: root
    password: Cgs8fu5q
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      keepalive-time: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  mvc:
    view:
      suffix: .html
      prefix: /

tencent:
  cos:
    secretId: wx0b311ec509dfac3b     # 替换为你的腾讯云 SecretId
    secretKey: 2f1b7c32b31a603da200e6bf8664d109   # 替换为你的 SecretKey
    region: ap-shanghai
    bucket: 7072-prod-3gavfsc66d765e5e-1306084687
    base-url: https://7072-prod-3gavfsc66d765e5e-1306084687.cos.ap-shanghai.myqcloud.com/


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted        # 实体字段名
      logic-delete-value: 1                # 删除时标记为 1
      logic-not-delete-value: 0            # 未删除标记为 0


wechat:
  appid: wx0b311ec509dfac3b
  secret: 2f1b7c32b31a603da200e6bf8664d109
